apiVersion: v1
kind: Namespace
metadata:
  name: example
  labels:
    name: example
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: example
    tier: frontend
  namespace: example
spec:
  type: LoadBalancer
  selector:
    app: example
    tier: frontend
  ports:
    - port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: example
    tier: backend
  namespace: example
spec:
  ports:
    - port: 8080
  selector:
    app: example
    tier: backend